export const APP_CONFIG = {
  BOOKING_FEE_PER_TICKET: 30,
  GST_PERCENTAGE: 0.18,
  MAX_TICKETS_PER_BOOKING: 10,
  DEFAULT_PAGE_SIZE: 8,
};

export const BRAND_COLORS = {
  PRIMARY: "#F84464",
  SECONDARY: "#2D2D2D",
  SUCCESS: "#10B981",
  WARNING: "#F59E0B",
  ERROR: "#EF4444",
};
